### PR TITLE
Added Video support

### PR DESCRIPTION
**Pull request by yusufusta**
Stories only supported photos. I have added support for adding videos to stories using `react-native-video`. If you want to add a video, just add `story_video` to dict.

### CODE REVIEW

**Comment by yusufusta** [comment]
@caglardurmus did you release to npm?

**Comment by caglardurmus** [comment]
Not right now

**Comment by yusufusta** [comment]
@caglardurmus need bug fix for rn video version.

**Comment by caglardurmus** [comment]
Did you fix the issue?

iPhone’umdan gönderildi

**Comment by IB3N** [comment]
@caglardurmus @yusufusta - what was the bug with react-native-video?

**Comment by IB3N** [comment]
@caglardurmus @yusufusta - ok so I tested this out and it seems to bring about a few bugs:

### if the first story of one user is a video, it starts playing from the moment it is rendered, which is immediately

- The implementation is pages of users (as one screen of the cube) which each contain pages of stories (`StoryListItem`)
- Is there a way to pass the current user page and that stories own user page number to each StoryListItem so that we can check if the current `StoryListItem` is in view, in order to do something like this:

```javascript
<Video
  ...
  paused={press || currentUserPage !== storyListItemUserPage}
/>
```

If possible, it would be good to check this for the `animationBar` animation, so that doesn't start and we could get rid of the repeated `progress.setValue(0)`. Because those animations all start as soon as the user stories are rendered, and given they are run on the javascript thread means this is a performance cost. for example:

```javascript
  function start() {
    // Only start this animation if this item is in view
    const isStoryInView = currentUserPage !== storyListItemUserPage
    if (!isStoryInView) {
      return;
    }

    setLoad(false);
    progress.setValue(0);
    startAnimation();
  }
```

### There is also a bug when pressing the right side of the screen to go next which fails, I am looking into this now

Would really appreciate any help possible, thanks 👍

**Pull request merged**
